-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Anamakine: localhost:3306
-- Üretim Zamanı: 10 Nis 2026, 18:23:09
-- Sunucu sürümü: 10.4.24-MariaDB
-- PHP Sürümü: 7.4.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `arad6551_sehir`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `sehirler`
--

CREATE TABLE `sehirler` (
  `id` int(11) NOT NULL,
  `sehir_adi` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `plaka_kodu` int(11) DEFAULT NULL,
  `meshur_yemek` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kisa_bilgi` text COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Tablo döküm verisi `sehirler`
--

INSERT INTO `sehirler` (`id`, `sehir_adi`, `plaka_kodu`, `meshur_yemek`, `kisa_bilgi`) VALUES
(1, 'Adana', 1, 'Adana Kebabı', 'Adana, Çukurova\'nın merkezinde yer alan bereketli bir tarım şehridir. Şehir, tarihi Taş Köprü ve modern Sabancı Merkez Camii ile tanınır. Gastronomi denilince akla gelen ilk lezzet Adana Kebabı ve şalgam suyudur. Seyhan ve Ceyhan nehirleri bölgeye hayat verir. Her yıl düzenlenen Portakal Çiçeği Karnavalı şehre büyük renk katar. Altın Koza Film Festivali ile Türk sinemasına büyük katkı sağlar. Akdeniz iklimi nedeniyle yazları oldukça sıcak geçer. Şehir, sanayi ve tarımın iç içe geçtiği güçlü bir ekonomiye sahiptir. Yaşar Kemal gibi pek çok önemli sanatçının memleketidir. Bölge halkı sıcakkanlılığı ve misafirperverliği ile bilinir.'),
(2, 'Adıyaman', 2, 'Çiğ Köfte', 'Adıyaman, Güneydoğu Anadolu Bölgesi\'nin tarihi ve kültürel zenginlikleriyle öne çıkan bir şehridir. Dünyanın sekizinci harikası olarak anılan Nemrut Dağı bu ilimizin sınırları içerisindedir. Kommagene Krallığı\'na ev sahipliği yapmış olan şehir, devasa heykelleriyle büyüleyici bir atmosfere sahiptir. Tarihi Cendere Köprüsü, Roma döneminden kalma ihtişamıyla günümüzde hala ayaktadır. Fırat Nehri\'nin bereketlendirdiği topraklarda tarım, ekonominin temel taşıdır. Atatürk Barajı\'nın bir kısmı şehrin sınırlarında yer alır ve bölgeye su kaynağı sağlar. Yöresel lezzetleri arasında çiğ köfte ve besni tavası büyük bir öneme sahiptir. Karakuş Tümülüsü ve Arsameia Antik Kenti, tarih meraklıları için vazgeçilmez duraklardır. Şehirde yazlar oldukça sıcak ve kurak, kışlar ise ılık ve yağışlı geçer.'),
(3, 'Afyonkarahisar', 3, 'Afyon Sucuğu ve Lokumu', 'Afyonkarahisar, Ege, Akdeniz ve İç Anadolu bölgelerinin kesişim noktasında yer alan önemli bir kavşak şehridir. Türkiye\'nin termal turizm başkenti olarak bilinen şehir, şifalı kaplıcalarıyla ünlüdür. Tarihi Karahisar Kalesi, şehrin merkezinde sarp bir kayalık üzerinde tüm ihtişamıyla yükselir. Kurtuluş Savaşı\'nın en kritik dönüm noktalarından olan Büyük Taarruz bu topraklarda başlamıştır. Dünya çapında tanınan Afyon lokumu ve sucuğu, şehrin gastronomi kültürünün en önemli simgeleridir. Frig Vadisi\'nin önemli bir kısmı bu şehrin sınırları içindedir ve peri bacalarıyla dikkat çeker. Mermer sektörü oldukça gelişmiş olup, şehrin mermerleri dünyanın dört bir yanına ihraç edilmektedir.'),
(4, 'Ağrı', 4, 'Abdigör Köftesi', 'Ağrı, Türkiye\'nin en doğusunda yer alan ve adını ülkenin en yüksek dağından alan sınır şehrimizdir. Efsanelere konu olan ve 5.137 metre yüksekliğindeki Ağrı Dağı, yılın her dönemi karlı zirvesiyle büyüleyicidir. Doğubayazıt ilçesinde bulunan İshak Paşa Sarayı, Osmanlı mimarisinin Anadolu\'daki en nadide örneklerinden biridir. Meteor Çukuru, dünyadaki en büyük meteor çukurlarından biri olarak doğa tutkunlarının ilgisini çeker. Diyadin kaplıcaları, dondurucu soğuklarda bile şifa arayanların uğrak noktasıdır. Şehirde kış ayları oldukça uzun, sert ve kar yağışlı geçerken, yazlar kısa ve serindir. Tarım ve hayvancılık, yöre halkının en önemli geçim kaynağını oluşturur.'),
(5, 'Aksaray', 68, 'Aksaray Tavası ve Sıkma', 'Aksaray, Kapadokya bölgesinin batı kapısı sayılan, Ihlara Vadisi ve heybetli Hasandağı ile öne çıkan tarihi bir şehirdir. Ihlara Vadisi, Melendiz Çayı\'nın aşındırmasıyla oluşmuş dik duvarları ve kayalara oyulmuş kiliseleriyle doğa ve tarih yürüyüşçülerinin gözdesidir. Eğri Minare, Selçuklu döneminden kalma kendine has duruşuyla şehrin en ilginç mimari yapılarından biridir. Tuz Gölü\'nün bir kısmına ev sahipliği yapan şehir, bembeyaz manzaralarıyla fotoğraf tutkunlarını cezbeder. Şehir merkezi, Selçuklu döneminin önemli bir ticaret ve konaklama noktası olan Sultanhanı ile ünlüdür.'),
(6, 'Amasya', 5, 'Amasya Elması', 'Amasya, Orta Karadeniz Bölgesi\'nde Yeşilırmak Vadisi boyunca uzanan tarihi bir şehirdir. Osmanlı döneminde şehzadelerin eğitim gördüğü yer olması nedeniyle \"Şehzadeler Şehri\" olarak anılır. Yeşilırmak\'ın iki yakasına dizilmiş geleneksel Yalıboyu Evleri, şehrin en ikonik manzaralarından birini sunar. Harşena Dağı yamaçlarına oyulmuş Pontus Kralları Kaya Mezarları, antik çağlardan günümüze ulaşan muazzam eserlerdir. Dünyaca ünlü Amasya elması, coğrafi işaret tescilli olup şehrin en önemli tarım ürünüdür. Kurtuluş Savaşı\'nın ilk adımlarının atıldığı Amasya Genelgesi, bu topraklarda ilan edilerek tarihe geçmiştir. Boraboy Gölü, doğa ile iç içe vakit geçirmek isteyenler için muhteşem bir manzara sunar.'),
(7, 'Ankara', 6, 'Ankara Tavası', 'Ankara, Türkiye Cumhuriyeti\'nin başkenti ve en kalabalık ikinci şehridir. Gazi Mustafa Kemal Atatürk\'ün anıt mezarı olan Anıtkabir bu topraklarda yer alır. Şehrin merkezinde yükselen Ankara Kalesi, geçmişten günümüze uzanan tarihi bir mirastır. Atakule, şehrin modern yüzünü yansıtan en önemli simgelerden biridir. Türkiye Büyük Millet Meclisi ve bakanlıkların bulunması nedeniyle ülkenin idari kalbidir. Karasal iklimin hakim olduğu şehirde kışlar soğuk, yazlar ise sıcak ve kurak geçer. Hacı Bayram Veli Camii ve Augustus Tapınağı, farklı kültürlerin bir arada yaşadığının kanıtıdır. Seğmenler ve Kuğulu Park gibi yeşil alanlar şehir sakinlerine nefes aldırır. Ankara kedisi, keçisi ve tavşanı dünya çapında bilinen endemik türlerdendir. Tarihi hamamönü evleri ise geleneksel Ankara mimarisinin en güzel örneklerini sunar.'),
(8, 'Antalya', 7, 'Antalya Piyazı', 'Antalya, Türkiye\'nin turizm başkenti olarak bilinen ve Akdeniz kıyısında yer alan büyüleyici bir şehirdir. Dünyaca ünlü Konyaaltı ve Lara plajları her yıl milyonlarca turisti ağırlar. Tarihi Kaleiçi bölgesi, dar sokakları ve cumbalı evleriyle ziyaretçileri geçmişe götürür. Roma döneminden kalma Hadrian Kapısı (Üç Kapılar), şehrin en önemli tarihi anıtlarından biridir. Şehir sınırları içinde yer alan Aspendos Antik Tiyatrosu, eşsiz akustiğiyle dünya çapında üne sahiptir. Düden ve Kurşunlu şelaleleri, doğa ile iç içe vakit geçirmek isteyenlerin gözdesidir. Yılın büyük bölümünde güneşli olan şehirde tipik Akdeniz iklimi görülür. Türkiye\'nin örtü altı tarım ve seracılık merkezlerinden biri olup, narenciye üretiminde başı çeker. Altın Portakal Film Festivali, Türk sinemasının en prestijli ödül törenidir. Toros Dağları\'nın eteğinde yer alan şehir, hem deniz hem de doğa sporları için idealdir.'),
(9, 'Ardahan', 75, 'Kaz Eti ve Ardahan Kaşarı', 'Ardahan, Türkiye\'nin en doğu ucunda, Kafkaslar\'a açılan kapısı olan, yüksek yaylaları ve soğuk iklimiyle bilinen bir sınır şehridir. Çıldır Gölü, kışın tamamen donarak üzerinde atlı kızakların gezindiği masalsı bir kış turizm merkezi haline gelir. Ardahan Kalesi, Osmanlı döneminden kalma heybetli yapısıyla Kura Nehri\'nin kenarında şehri selamlar. Şehir, Türkiye\'nin en kaliteli çiçek ballarından birine ve yüksek rakımlı yaylalarında beslenen hayvanlardan elde edilen lezzetli süt ürünlerine sahiptir. Yalnızçam Kayak Merkezi, kristal kar yapısıyla kayak tutkunları için yeni bir keşif noktasıdır.'),
(10, 'Artvin', 8, 'Kuymak', 'Artvin, Karadeniz Bölgesi\'nin en doğusunda yer alan ve muazzam doğasıyla öne çıkan bir şehirdir. Şehrin ortasından geçen Çoruh Nehri, dünyanın en hızlı akan nehirlerinden biri olup rafting tutkunlarının gözdesidir. Kaçkar Dağları ve Karagöl gibi doğal güzellikler, şehri bir yeryüzü cenneti haline getirir. Macahel bölgesi, bozulmamış biyolojik çeşitliliği ile UNESCO tarafından biyosfer rezerv alanı ilan edilmiştir. Sarp yamaçlara kurulu olan şehir merkezi, virajlı yolları ve derin vadileriyle dikkat çeker. Geleneksel ahşap mimarisiyle inşa edilmiş yayla evleri, bölge kültürünün önemli bir parçasıdır. Karadeniz ikliminin etkisiyle her mevsim bol yağış alır ve yemyeşil bir bitki örtüsüne sahiptir. Deriner Barajı, Türkiye\'nin en yüksek, dünyanın ise sayılı yüksek barajlarından biridir. Kafkasör Yaylası\'nda her yıl düzenlenen geleneksel boğa güreşleri büyük ilgi görür. Tarihi köprüleri ve kiliseleriyle Artvin, doğa ve tarih severler için eşsiz bir rotadır.'),
(11, 'Aydın', 9, 'Aydın İnciri ve Keşkek', 'Aydın, Ege Bölgesi\'nin verimli Büyük Menderes Havzası üzerinde kurulu, tarihi ve tarımsal zenginliği yüksek bir şehirdir. Dünyaca ünlü Aydın inciri, coğrafi işaret tesciliyle şehrin en önemli ihracat ürünüdür. Kuşadası ve Didim gibi popüler tatil beldeleri, yaz turizminin kalbinin attığı yerlerdendir. Antik çağların en önemli filozof ve matematikçilerinden Thales ve Miletoslu diğer bilginler bu topraklarda yaşamıştır. Afrodisias Antik Kenti, UNESCO Dünya Mirası Listesi\'nde yer alan muazzam bir sanat ve heykel merkezidir. Apollon Tapınağı ve Priene Antik Kenti, geçmişin görkemini günümüze taşıyan eşsiz yapılardır. Şehir, zeytin ve zeytinyağı üretiminde Türkiye\'nin lider konumundaki illerinden biridir. Geleneksel Efe ve Zeybek kültürü, Aydın\'ın folklorik zenginliğinin en belirgin yansımasıdır. Tipik Ege iklimi sayesinde kışlar ılık, yazlar ise oldukça sıcak geçer. Yöresel lezzetlerin baş tacı olan düğün keşkeği, şehrin kültürel mirasının ayrılmaz bir parçasıdır.'),
(12, 'Balıkesir', 10, 'Höşmerim ve Ayvalık Tostu', 'Balıkesir, hem Marmara hem de Ege Denizi\'ne kıyısı olan nadir şehirlerimizden biridir. Şehir, bereketli ovaları sayesinde tarım ve hayvancılık alanında Türkiye\'nin önemli merkezlerindendir. Ayvalık, Cunda Adası, Edremit ve Akçay gibi turistik ilçeleriyle yaz aylarında büyük bir yoğunluk yaşar. Kaz Dağları (İda Dağı), mitolojik efsanelere konu olmuş ve dünyanın en bol oksijenli alanlarından biridir. Tarihi Saat Kulesi ve Zağnos Paşa Camii, Balıkesir kent merkezinin simge yapılarıdır. Marmara Adası ve Avşa Adası, deniz turizmi açısından bölgenin cazibe merkezleridir. Yöresel tatlısı höşmerim, peynir ve irmiğin eşsiz uyumuyla herkesin beğenisini kazanır. Kaplıcaları ve termal tesisleriyle sağlık turizminde de oldukça iddialı bir konumdadır. Kuş Cenneti Milli Parkı, her yıl yüzlerce farklı kuş türüne ev sahipliği yaparak doğa bilimcilerini ağırlar. Susurluk ilçesi ise meşhur ayranı ve tostuyla yol üstü lezzet duraklarının vazgeçilmez adresidir.'),
(13, 'Bartın', 74, 'Amasra Salatası ve Bartın Pidesi', 'Bartın, Karadeniz\'in en güzel koylarından biri olan Amasra\'ya ev sahipliği yapan, yeşilin denizle kucaklaştığı huzurlu bir sahil şehridir. Amasra, tarihi kalesi, dar sokakları ve taze balık restoranlarıyla turizmin incisi konumundadır. Şehrin ortasından geçen ve üzerinde taşımacılık yapılabilen tek akarsu olan Bartın Çayı, şehre Venedik vari bir hava katar. İnkumu, uzun ve kumluk plajıyla Batı Karadeniz\'in en popüler deniz tatili rotalarından biridir. Şehir, tarihi ahşap evleri ve el yapımı \"Tel Kırma\" sanatı ile geleneksel dokusunu titizlikle korumaktadır.'),
(14, 'Batman', 72, 'Batman Şam Böreği ve Perde Pilavı', 'Batman, 1940\'larda petrolün bulunmasıyla hızla büyüyen, modern silueti ile antik tarihini bir arada barındıran bir Mezopotamya şehridir. Hasankeyf, Dicle Nehri kıyısında binlerce yıllık mağaraları ve taş eserleriyle tarihin en eski tanıklarından biridir. Batman Çayı üzerinde kurulu tarihi Malabadi Köprüsü, dünyanın en geniş taş kemerine sahip mühendislik harikalarından biridir. Şehir, Raman Dağı etrafındaki petrol kuyuları sayesinde Türkiye ekonomisine hayati bir katkı sağlar. Gelişen sanayisi ve genç nüfusuyla bölgenin dinamik ticaret ve eğitim merkezlerinden biridir.'),
(15, 'Bayburt', 69, 'Lor Dolması ve Galacoş', 'Bayburt, Çoruh Nehri\'nin ikiye böldüğü, sarp kaleleri ve yüksek rakımlı yaylalarıyla bilinen huzurlu bir Karadeniz-Anadolu geçiş şehridir. Bayburt Kalesi, şehrin en görkemli yapısı olup \"Çin Maçın Kalesi\" olarak da adlandırılan devasa bir savunma anıtıdır. Baksı Müzesi, modern sanat ile geleneksel el sanatlarını bir köy tepesinde birleştiren, Avrupa Konseyi Müze Ödülü sahibi sıra dışı bir kültür merkezidir. Kenan Yavuz Etnografya Müzesi, Anadolu\'nun kaybolmaya yüz tutmuş geleneklerini yaşatan ödüllü bir duraktır. Şehir, kış aylarında karın sessizliğiyle, yazın ise Çoruh\'un coşkun akışıyla büyüleyicidir.'),
(16, 'Bilecik', 11, 'Bilecik Mantısı (Nohutlu)', 'Bilecik, Osmanlı İmparatorluğu\'nun temellerinin atıldığı, tarihin ve kültürün harmanlandığı stratejik bir şehirdir. Söğüt ilçesinde bulunan Ertuğrul Gazi Türbesi, şehrin manevi merkezidir. Şeyh Edebali Türbesi ise \"İnsanı yaşat ki devlet yaşasın\" düsturunun doğduğu yer olarak bilinir. Sakarya Nehri\'nin suladığı verimli toprakları, mermer yatakları ve seramik sanayisi ile ekonomiye katkı sağlar. Pelitözü Göleti, doğa ile iç içe vakit geçirmek isteyenlerin uğrak noktasıdır.'),
(17, 'Bingöl', 12, 'Çobantaşı Kavurması', 'Bingöl, Doğu Anadolu\'nun sarp dağları ve eşsiz doğa olaylarıyla tanınan huzurlu bir şehridir. Solhan ilçesindeki Yüzen Adalar, dünyada nadir görülen doğa harikalarından biridir ve yerli turistlerin ilgisini çeker. Kış aylarında Hesarek Kayak Merkezi, bölgenin önemli kış turizmi duraklarından biri haline gelir. Şehir, yüksek rakımlı yaylaları ve kaliteli süzme balıyla ünlüdür. Güneşin doğuşunun en güzel izlendiği yerlerden biri olan Kala Tepe, her yıl festivallere ev sahipliği yapar.'),
(18, 'Bitlis', 13, 'Büryan Kebabı', 'Bitlis, \"Beş Minareli Şehir\" olarak bilinen, kadim tarihi ve Nemrut Krater Gölü ile ünlü bir yerleşimdir. Van Gölü kıyısındaki Ahlat ilçesi, \"Selçuklu Meydan Mezarlığı\" ile dünyanın en büyük Türk-İslam mezarlığına ev sahipliği yapar. Şehrin tarihi dokusunu yansıtan taş evler ve Bitlis Kalesi, geçmişin izlerini günümüze taşır. Nemrut Krater Gölü, dünyanın en büyük ikinci krater gölü olup doğa yürüyüşçüleri için vazgeçilmezdir. Kışın yoğun kar yağışı alan şehir, geleneksel el sanatları ve dokumalarıyla da tanınır.'),
(19, 'Bolu', 14, 'Abant Kebabı ve Mengen Pilavı', 'Bolu, Türkiye\'nin mutfak kültürü denilince akla gelen ilk şehri ve doğa harikası bir merkezidir. Mengenli aşçıları dünya çapında nam salmış olup Osmanlı saray mutfağından bu yana geleneği sürdürürler. Abant, Yedigöller ve Gölcük gibi tabiat parkları, her mevsim farklı bir renk cümbüşü sunan kartpostallık manzaralara sahiptir. Batı Karadeniz\'in en yüksek zirvelerinden biri olan Kartalkaya, Türkiye\'nin en önemli kayak merkezlerinden biridir. Şehir, gür ormanları, termal suları ve temiz havasıyla tam bir dinlenme rotasıdır.'),
(20, 'Burdur', 15, 'Burdur Şiş', 'Burdur, \"Göller Yöresi\"nin kalbinde yer alan, antik kentleri ve doğa harikası gölleriyle büyüleyen bir şehirdir. \"Türkiye\'nin Maldivleri\" olarak anılan Salda Gölü, bembeyaz kumsalı ve turkuaz suyuyla dünya çapında bir şöhrete sahiptir. Sagalassos Antik Kenti, Roma döneminden kalma muazzam tiyatrosu ve halen akan Antoninler Çeşmesi ile tarih tutkunlarını ağırlar. Şehir, teke yöresi kültürünün merkezi olup bağlama ve sipsi eşliğindeki halk oyunlarıyla bilinir. Burdur Gölü, göçmen kuşların uğrak noktası olan önemli bir ekosistemdir.'),
(21, 'Bursa', 16, 'İskender Kebap ve İnegöl Köfte', 'Bursa, Osmanlı İmparatorluğu\'nun ilk başkenti, sanayinin ve yeşilin birleştiği bir metropoldür. Uludağ, Türkiye\'nin en köklü kış sporları merkezi olarak şehre her kış canlılık katar. UNESCO Dünya Mirası Listesi\'ndeki Cumalıkızık köyü, Osmanlı sivil mimarisinin en iyi korunmuş örneklerini sunar. Tarihi İpek Yolu üzerinde bulunan Koza Han, ipek böcekçiliği geleneğinin kalbi olmaya devam etmektedir. Şehir; Ulu Camii, Yeşil Türbe ve Tophane gibi anıt eserleriyle \"Yeşil Bursa\" unvanını sonuna kadar hak eden kültürel bir hazinedir.'),
(22, 'Çanakkale', 17, 'Peynir Helvası ve Sardalya', 'Çanakkale, tarihin akışını değiştiren destanların yazıldığı, iki kıtayı birbirine bağlayan stratejik bir şehirdir. Gelibolu Yarımadası Tarihi Milli Parkı, Çanakkale Savaşları\'nın hatıralarını taşıyan şehitlikleri ve anıtlarıyla milli bir bilinç merkezidir. Homeros\'un İlyada destanına konu olan antik Troya kenti, binlerce yıllık geçmişiyle UNESCO listesinde yer alır. Bozcaada ve Gökçeada, berrak denizleri ve bağcılık kültürüyle Ege\'nin en huzurlu duraklarındandır. Çanakkale Boğazı üzerindeki yeni asma köprü, modern Türkiye\'nin simgelerinden biri olarak şehre değer katmıştır.'),
(23, 'Çankırı', 18, 'Yaren Güveci ve Ezme Lahana', 'Çankırı, İç Anadolu\'nun köklü \"Yaren\" kültürü ve devasa yer altı tuz mağarasıyla bilinen karakteristik bir şehridir. Hititlerden bu yana kullanılan Yer Altı Tuz Şehri, içindeki tuzdan heykelleri ve galerileriyle bambaşka bir dünya sunar. Şehir merkezi, Selçuklu dönemi eserlerinden olan Taş Mescit gibi tarihi yapılarla süslüdür. Ilgaz Dağları, kışın kayak, yazın ise yayla turizmi ile doğaseverleri ağırlar. Yarenlik geleneği, şehrin sosyal dokusunda yardımlaşma ve disiplini temsil eden yaşayan bir miras olarak sürdürülmektedir.'),
(24, 'Çorum', 19, 'Çorum Leblebisi ve İskilip Dolması', 'Çorum, Anadolu\'nun en eski medeniyetlerinden biri olan Hitit İmparatorluğu\'na başkentlik yapmış kadim bir şehirdir. Hattuşaş ve Yazılıkaya, devasa şehir surları ve aslanlı kapılarıyla tarihin derinliklerine bir yolculuk sunar. Şehir, leblebisiyle dünya çapında bir ün kazanmış olsa da mutfağındaki İskilip Dolması gibi ağır lezzetlerle de dikkat çeker. Selçuklu ve Osmanlı döneminden kalma tarihi saat kulesi ve camileri, şehir merkezine karakter kazandırır. İncesu Kanyonu, hem tarihi kalıntıları hem de doğa yürüyüşü parkurlarıyla son yılların gözde rotalarındandır.'),
(25, 'Denizli', 20, 'Denizli Kebabı', 'Denizli, bembeyaz travertenleri ve tekstil sanayisiyle dünyaya açılan bir Ege şehridir. UNESCO Dünya Mirası Listesi\'ndeki Pamukkale ve yanı başındaki Hierapolis Antik Kenti, termal suları ve şifalı havuzlarıyla eşsizdir. Laodikya Antik Kenti, Hristiyanlık tarihi açısından önemli yedi kiliseden birine ev sahipliği yapar. Şehrin simgesi olan Denizli Horozu, kendine has ötüşü ve heybetli duruşuyla bilinir. Tekstil sektöründeki başarısı sayesinde havlu ve bornoz üretiminde dünyanın sayılı merkezlerinden biri olup, modern alışveriş merkezleri ve parklarıyla gelişmiş bir kent yapısına sahiptir.'),
(26, 'Diyarbakır', 21, 'Meftune ve Ciğer Kebabı', 'Diyarbakır, 9 bin yıllık geçmişiyle Mezopotamya\'nın en önemli ticaret ve kültür merkezlerinden biridir. UNESCO Dünya Mirası Listesi\'nde yer alan Diyarbakır Surları, dünyanın en uzun ve en sağlam surları arasındadır. Surların eteğindeki Hevsel Bahçeleri, binlerce yıldır verimliliğini koruyan bir doğa harikasıdır. Tarihi On Gözlü Köprü, Dicle Nehri üzerinde şehrin siluetini tamamlayan en önemli simgedir. Şehir; hanları, camileri ve dar sokaklarıyla tarih kokan bir atmosfere sahip olup, misafirperverliği ve zengin mutfak kültürüyle ünlüdür.'),
(27, 'Düzce', 81, 'Düzce Acıkası ve Çerkez Tavuğu', 'Düzce, Karadeniz ile Marmara arasında, yaylaları, şelaleleri ve antik kentleriyle saklı kalmış bir doğa ve tarih cennetidir. Akçakoca sahil ilçesi, temiz plajları ve Ceneviz Kalesi ile Karadeniz\'in deniz turizmi kapısıdır. Konuralp (Prusias ad Hypium) antik tiyatrosu, bölgenin Roma dönemindeki ihtişamlı sanat yaşamını günümüze taşıyan en sağlam yapılardan biridir. Samandere ve Güzeldere şelaleleri, ormanın derinliklerinde gürleyen sularıyla huzur veren duraklardır. Şehir, fındık üretimi ve mobilya sanayisindeki başarısıyla gelişmiş, kültürel çeşitliliğiyle zengin bir yapıya sahiptir.'),
(28, 'Edirne', 22, 'Tava Ciğer', 'Edirne, Osmanlı İmparatorluğu\'na yaklaşık bir asır başkentlik yapmış, Avrupa\'ya açılan tarihi bir sınır şehridir. Mimar Sinan\'ın \"ustalık eserim\" dediği Selimiye Camii, şehrin her noktasından görülen muazzam bir şaheserdir. Her yıl düzenlenen tarihi Kırkpınar Yağlı Güreşleri, asırlık bir geleneği günümüze taşır. Meriç ve Tunca nehirleri üzerindeki tarihi köprüler, gün batımında eşsiz manzaralar sunar. Tarihi çarşıları, eski camileri ve badem ezmesi gibi yöresel tatlarıyla Edirne, adeta bir açık hava müzesi niteliğindedir.'),
(29, 'Elazığ', 23, 'Harput Köftesi ve Gömme', 'Elazığ, antik Harput Kenti\'nin mirasını taşıyan, Doğu Anadolu\'nun gelişmiş ve kültürel birikimi yüksek bir şehridir. Harput Kalesi ve eğri minaresiyle ünlü Ulu Camii, şehrin tarihsel derinliğini yansıtır. Hazar Gölü, çevresindeki tesislerle bölgenin adeta denizi konumundadır ve su sporları için imkan sağlar. Keban Barajı, Türkiye\'nin en büyük enerji projelerinden biri olup, çevresindeki balık restoranlarıyla bilinir. Şehir, \"Gakgoşlar\" diyarı olarak anılır ve kendine has kürsübaşı geleneği ile musikisiyle tanınır.'),
(30, 'Erzincan', 24, 'Erzincan Döneri ve Tulum Peyniri', 'Erzincan, Fırat Nehri\'nin geçtiği verimli ovaları ve heybetli dağlarıyla tanınan bir Doğu Anadolu şehridir. Şehir, yaşadığı büyük depremlerden sonra modern ve düzenli bir şehir planıyla yeniden inşa edilmiştir. Kemaliye (Eğin) ilçesi, Karanlık Kanyon ve tarihi evleriyle UNESCO geçici listesinde yer alan turistik bir cevherdir. Girlevik Şelalesi, kışın donan buz sarkıtlarıyla, yazın ise serinliğiyle doğaseverleri cezbeder. Kaliteli tulum peyniri ve bakır işlemeciliği, şehrin en önemli ticari ve kültürel markaları arasındadır.'),
(31, 'Erzurum', 25, 'Cağ Kebabı ve Kadayıf Dolması', 'Erzurum, \"Dadaşlar diyarı\" olarak bilinen, yüksek rakımlı yaylaları ve köklü tarihiyle Anadolu\'nun kilit şehirlerinden biridir. Selçuklu mimarisinin en zarif örneklerinden Çifte Minareli Medrese, şehrin gurur kaynağıdır. Palandöken Kayak Merkezi, dünya standartlarındaki pistleriyle Türkiye\'nin en önemli kış turizm destinasyonlarından biridir. Milli Mücadele döneminde Erzurum Kongresi\'ne ev sahipliği yaparak Cumhuriyet\'in temellerinin atılmasında kritik rol oynamıştır. Oltu taşı işlemeciliği, şehrin en zarif el sanatı olarak dünya çapında bilinir.'),
(32, 'Eskişehir', 26, 'Çibörek ve Balaban Köfte', 'Eskişehir, Porsuk Çayı etrafında şekillenen modern yapısı ve dinamik öğrenci nüfusuyla \"Türkiye\'nin Venedik\'i\" olarak anılır. Odunpazarı evleri, restore edilmiş renkli sokaklarıyla geleneksel mimariyi ve sanat atölyelerini bir araya getirir. Sazova Parkı ve Balmumu Heykeller Müzesi, şehrin turistik cazibesini artıran modern projelerdir. Lületaşı işlemeciliği, Eskişehir\'e özgü nadir bir el sanatı olarak varlığını sürdürür. Şehir; temalı parkları, bisiklet yolları ve gelişmiş kültürel yaşamıyla Türkiye\'nin en yaşanabilir kentleri listesinde her zaman üst sıralarda yer alır.'),
(33, 'Gaziantep', 27, 'Baklava ve Beyran', 'Gaziantep, gastronomi alanında UNESCO yaratıcı şehirler ağına dahil edilmiş, dünyanın lezzet başkentlerinden biridir. Zeugma Mozaik Müzesi, \"Çingene Kızı\" mozaiği gibi eşsiz eserlerle dünyanın en önemli mozaik koleksiyonlarından birine ev sahipliği yapar. Şehir, tarihi bakırcılar çarşısı ve kalesiyle kadim ticaret yollarının izlerini taşır. Antep fıstığı üretimi ve fıstıklı tatlılarıyla ekonominin ve lezzetin kalbi durumundadır. Kurtuluş Savaşı\'ndaki kahramanca mücadelesiyle \"Gazi\" unvanını almış, bugün ise sanayisi ve ticaretiyle bölgenin parlayan yıldızıdır.'),
(34, 'Giresun', 28, 'Karalahana Çorbası ve Giresun Simidi', 'Giresun, Karadeniz\'in masmavi suları ile yemyeşil dağlarının kucaklaştığı, fındığın anavatanı olarak kabul edilen bir şehirdir. Şehrin hemen karşısındaki Giresun Adası, Karadeniz\'in tek yaşanabilir adası olup mitolojik hikayelere konu olmuştur. Kümbet ve Bektaş yaylaları, bulutların üzerindeki manzaralarıyla yayla turizminin önemli merkezlerindendir. Tarihi Giresun Kalesi, şehri tepeden izlemek isteyenler için harika bir manzara sunar. Dünyanın en kaliteli fındığının yetiştiği bu topraklar, kirazın dünyaya yayıldığı yer olarak da tarihi kayıtlarda yer alır.'),
(35, 'Gümüşhane', 29, 'Pestil ve Köme', 'Gümüşhane, derin vadileri ve antik maden yataklarıyla bilinen, Doğu Karadeniz\'in iç kesimlerinde saklı bir coğrafyadır. Karaca Mağarası, içindeki sarkıt ve dikitlerin estetik güzelliği ile \"yer altı sarayı\" olarak nitelendirilir. Tarihi İpek Yolu üzerindeki Zigana Geçidi, modern tüneliyle Karadeniz\'i iç kısımlara bağlayan hayati bir noktadır. Süleymaniye Mahallesi (Eski Gümüşhane), camileri ve kiliseleriyle geçmişteki çok kültürlü yapısını koruyan bir sit alanıdır. Şehir, yüksek proteinli pestil ve köme üretimiyle doğal atıştırmalıklar konusunda markadır.'),
(36, 'Hakkari', 30, 'Doğaba ve Otlu Peynir', 'Hakkari, Türkiye\'nin en sarp dağlarına ve en yüksek zirvelerine sahip, doğasıyla hayranlık uyandıran bir sınır şehridir. Cilo Dağları ve üzerindeki buzullar, dağcılık ve doğa sporları için zorlu ama bir o kadar da büyüleyici bir ortam sunar. Zap Suyu\'nun hırçın akışıyla şekillenen vadiler, şehrin coğrafi karakterini belirler. Şehir, özgün dokumaları olan Hakkari kilimleri ve şifa kaynağı yüksek rakımlı balıyla tanınır. Ters Lale (Ağlayan Gelin), dünyada sadece bu bölgeye özgü endemik bir tür olarak şehrin simgesidir.'),
(37, 'Hatay', 31, 'Künefe ve Tepsi Kebabı', 'Hatay, binlerce yıllık geçmişiyle \"Medeniyetler Sofrası\" olarak bilinen, barış ve hoşgörünün merkezidir. Dünyanın en büyük mozaik müzelerinden biri olan Hatay Arkeoloji Müzesi, şehrin zengin tarihini gözler önüne serer. St. Pierre Kilisesi, Hristiyanlık tarihinin en eski ibadethanelerinden biri olarak kabul edilir. Titus Tüneli ve Beşikli Mağara, Roma döneminin mühendislik harikalarıdır. Gastronomi şehri unvanına sahip olan Hatay, baharatlı yemekleri ve meşhur künefesiyle ziyaretçilerine unutulmaz bir lezzet şöleni sunar.'),
(38, 'Iğdır', 76, 'Bozbaş ve Iğdır Kaysısı', 'Iğdır, heybetli Ağrı Dağı\'nın eteklerinde kurulu, üç ülkeye (Ermenistan, Nahçıvan ve İran) komşu olan tek şehrimizdir. Bölgenin genel sert ikliminin aksine \"Doğu\'nun Çukurova\'sı\" olarak bilinen ılıman mikroklimal yapısı sayesinde pamuk ve meyve yetişir. Şehir, her yıl binlerce leyleğin ve göçmen kuşun uğradığı, Aras Nehri\'nin suladığı verimli topraklara sahiptir. Iğdır kaysısı, aroması ve lezzetiyle Malatya kaysısından farklı olarak sofralık bir değer sunar. Ağrı Dağı\'nın görkemli manzarası, şehrin her noktasından izlenebilen devasa bir doğal tablodur.'),
(39, 'Isparta', 32, 'Fırın Kebabı ve Kabune Pilavı', 'Isparta, \"Güller ve Göller Diyarı\" olarak anılan, kokusuyla ve doğasıyla büyüleyen bir Akdeniz şehridir. Dünya gül yağı üretiminin büyük bir kısmını karşılayan şehirde, gül hasadı zamanı eşsiz manzaralar oluşur. Son yıllarda lavanta bahçeleriyle de (Kuyucak Köyü) adından söz ettiren Isparta, ekoturizmin yükselen yıldızıdır. Eğirdir Gölü, berrak suyu ve içindeki Can Adası ile bölgenin en popüler dinlenme alanıdır. Davraz Dağı Kayak Merkezi, kışın hem amatör hem profesyonel kayakçıları ağırlayan modern bir tesistir.'),
(40, 'İstanbul', 34, 'Sultanahmet Köftesi ve Balık Ekmek', 'İstanbul, Asya ile Avrupa\'yı birleştiren, üç imparatorluğa başkentlik yapmış dünyanın en büyüleyici metropollerinden biridir. Ayasofya, Topkapı Sarayı ve Sultanahmet Camii gibi anıt yapılar, şehrin tarihi yarımadasını bir mücevher gibi süsler. Boğaz Köprüleri ve Galata Kulesi, şehrin eşsiz siluetinin ayrılmaz parçalarıdır. Beşiktaş ve Kadıköy gibi dinamik bölgeleriyle hem ticaretin hem de modern yaşamın kalbi durumundadır. Adalar\'ın huzuruyla Beyoğlu\'nun dinamizmini bir arada sunan İstanbul, her sokağında ayrı bir hikaye barındıran yaşayan bir tarihtir.'),
(41, 'İzmir', 35, 'Boyoz, Kumru ve İzmir Köfte', 'İzmir, \"Ege\'nin İncisi\" olarak bilinen, modern yaşam tarzı, tarihi zenginliği ve masmavi körfeziyle büyüleyici bir şehirdir. Kordon Boyu ve Tarihi Saat Kulesi, İzmir denilince akla gelen ilk simgelerdir. Antik dünyanın yedi harikasından biri olan Artemis Tapınağı\'nın bulunduğu Efes Antik Kenti, şehrin tarihsel gücünü yansıtır. Çeşme, Alaçatı ve Urla gibi ilçeleri, deniz turizmi ve gastronomi rotalarıyla dünya çapında popülerdir. Kemeraltı Çarşısı, asırlardır süregelen ticaret geleneğiyle şehrin en canlı ve renkli noktası olmaya devam etmektedir.'),
(42, 'Kahramanmaraş', 46, 'Maraş Dondurması ve Eli Böğründe', 'Kahramanmaraş, dünyaca ünlü dövme dondurması ve Kurtuluş Savaşı\'ndaki kahramanca direnişiyle tanınan kadim bir Anadolu şehridir. Keçi sütü ve salep ile hazırlanan dondurması, şehre global bir marka değeri kazandırmıştır. Tarihi çarşıları, geleneksel el sanatlarından olan bakırcılık ve kuyumculuk alanında halen canlılığını korur. Germenicia Antik Kenti mozaikleri, şehrin Roma dönemindeki ihtişamlı yaşamını gün yüzüne çıkarmıştır. Şehir, baraj gölleri ve yaylalarıyla aynı zamanda Doğu Akdeniz\'in doğal güzelliklerini barındırır.'),
(43, 'Karabük', 78, 'Safranbolu Bükmesi ve Safranlı Lokum', 'Karabük, Türkiye\'nin ilk ağır sanayi hamlesiyle (Kardemir) kurulan, ancak Safranbolu gibi dünya mirası bir hazineye sahip olan özel bir şehirdir. UNESCO Dünya Mirası Listesi\'ndeki Safranbolu Evleri, Osmanlı mimarisinin ve geleneksel yaşamın en iyi korunduğu dünyadaki nadir yerlerdendir. Kristal Teras ve Tokatlı Kanyonu, adrenalin ve doğa manzarasını birleştiren modern turizm noktalarıdır. Yenice Ormanları, biyoçeşitliliği ve el değmemiş yapısıyla \"orman denizi\" olarak nitelendirilir. Şehir, demir-çelik sanayisiyle ülkenin kalkınmasına omuz verirken, tarihiyle de dünyaya kapılarını açar.'),
(44, 'Karaman', 70, 'Batırık ve Callaba', 'Karaman, Türkçenin resmi dil olarak ilan edildiği (Karamanoğlu Mehmet Bey), tarihi ve kültürel derinliği olan kadim bir Anadolu şehridir. Şehir, Orta Çağ\'ın inanç merkezi olan \"Binbir Kilise\" ve heybetli Karaman Kalesi gibi tarihi hazinelere ev sahipliği yapar. Taşkale ve Manazan Mağaraları, kayalara oyulmuş tahıl ambarları ve yerleşim alanlarıyla insan zekasının doğayla uyumunu gösterir. Elma üretimi ve bisküvi sanayisiyle ekonomiye yön veren Karaman, İç Anadolu\'nun sessiz ama üretken bir merkezidir. Yunus Emre\'nin türbesinin bulunduğu şehir, manevi atmosferiyle de bilinir.'),
(45, 'Kars', 36, 'Kaz Eti ve Kars Gravyeri', 'Kars, Doğu Anadolu\'nun en yüksek ve kışın en çok yakıştığı şehirlerinden biri olup, Rus mimarisinin izlerini taşıyan sokaklarıyla ünlüdür. UNESCO Dünya Mirası Listesi\'ndeki Ani Arabeleri, \"Binbir Kilise Şehri\" olarak bilinen kadim bir yerleşimdir. Kış aylarında donan Çıldır Gölü üzerinde atlı kızaklarla gezinti yapmak, şehre gelenlerin en sevdiği aktivitelerden biridir. Sarıkamış, kristal kar yapısıyla dünya standartlarında bir kayak merkezi sunar. Şehir, kaşar peyniri ve gravyeriyle Türkiye\'nin peynir ambarı olarak kabul edilir.'),
(46, 'Kastamonu', 37, 'Etli Ekmek ve Banduma', 'Kastamonu, Batı Karadeniz\'in gür ormanları, tarihi konakları ve milli mücadele ruhunu taşıyan \"İstiklal Yolu\" ile bilinen bir şehridir. Küre Dağları Milli Parkı ve Valla Kanyonu, dünyanın sayılı kanyonlarından biri olup doğa tutkunlarını ağırlar. Şehir merkezi, Selçuklu ve Osmanlı mimarisinin en güzel örneklerini taşıyan konaklarıyla adeta bir müze gibidir. Taşköprü sarımsağı, kalitesi ve aromasıyla dünya çapında tescilli bir lezzettir. Cide ve İnebolu gibi sahil ilçeleri, yeşil ile mavinin birleştiği huzurlu bir Karadeniz atmosferi sunar.'),
(47, 'Kayseri', 38, 'Mantı, Pastırma ve Sucuk', 'Kayseri, Erciyes Dağı\'nın gölgesinde yükselen, ticaretin ve sanayinin Anadolu\'daki en eski merkezlerinden biridir. Heybetli Erciyes Kayak Merkezi, kış turizminin gözbebeği olup modern tesisleriyle her yıl binlerce turisti ağırlar. Selçuklu dönemine ait Gevher Nesibe Şifahanesi, dünyanın ilk tıp merkezlerinden biri olarak kabul edilir. Kapuzbaşı Şelaleleri, dünyanın en yüksekten dökülen şelalelerinden biri olarak muazzam bir doğa olayı sunar. Şehir, girişimci ruhu ve sofraların baş tacı olan pastırmasıyla Türkiye ekonomisinin önemli bir aktörüdür.'),
(48, 'Kırıkkale', 71, 'Keskin Tava', 'Kırıkkale, Türkiye Cumhuriyeti\'nin savunma sanayi hamlesiyle büyüyen, Ankara\'nın doğu kapısı niteliğindeki stratejik bir şehirdir. Makine ve Kimya Endüstrisi (MKE) fabrikalarıyla şehrin kimliği şekillenmiş, \"Sanayi Şehri\" unvanını almıştır. Silah Müzesi, savunma sanayisinin tarihsel gelişimini yansıtan Türkiye\'nin sayılı müzelerinden biridir. Kızılırmak\'ın geçtiği topraklar üzerinde kurulu olan şehir, vadi manzaraları ve mesire alanlarıyla dinlenme noktaları sunar. Keskin ilçesi, bozlak geleneği ve tarihi konaklarıyla şehrin kültürel ruhunu temsil eder.'),
(49, 'Kırklareli', 39, 'Kırklareli Köftesi ve Hardaliye', 'Kırklareli, Trakya\'nın kuzeyinde yer alan, Istranca Dağları\'nın eteğinde doğa ile tarihin iç içe geçtiği huzurlu bir şehirdir. İğneada Longoz Ormanları, dünyada nadir görülen ekosistemiyle doğaseverlerin en uğrak yerlerinden biridir. Dupnisa Mağarası, Trakya\'nın turizme açılan ilk mağarası olup içindeki büyüleyici oluşumlarla dikkat çeker. Şehir, bağcılık geleneği ve fermente bir içecek olan Hardaliye üretimiyle ünlüdür. Kıyıköy gibi balıkçı köyleri, hem denizi hem de tarihi kalıntılarıyla hafta sonu kaçamakları için idealdir.'),
(50, 'Kırşehir', 40, 'Çullama ve Kırşehir Köftesi', 'Kırşehir, Anadolu\'nun manevi mimarlarından Ahi Evran ve Neşet Ertaş\'ın memleketi olarak \"Ozanlar Şehri\" unvanını taşır. Ahilik teşkilatının temellerinin atıldığı şehir, esnaflık geleneğini ve kültürel disiplini günümüzde de hissettirir. Cacabey Medresesi, döneminin astronomi merkezi olarak kubbesindeki gökyüzü gözlem detaylarıyla eşsiz bir yapıdır. UNESCO tarafından tescillenen müzik kültürü, bozlakların yanık sesiyle şehrin her köşesinde yankılanır. Kaman ilçesi, dünyaca ünlü ince kabuklu ceviziyle tarımsal bir değer sunar.'),
(51, 'Kilis', 79, 'Kilis Tavası ve Oruk Kebabı', 'Kilis, Güneydoğu Anadolu ile Suriye sınırı arasında yer alan, zeytin bahçeleri ve üzüm bağlarıyla çevrili kadim bir şehirdir. Şehir, yüzyıllardır süregelen \"Kilis Zeytinyağı\" üretimiyle dünyaca ünlü, yüksek polifenollü ve lezzetli yağlar sunar. Tarihi Ravanda Kalesi, bölgenin savunma hattındaki stratejik önemini günümüze taşıyan önemli bir eserdir. Kilis mutfağı, Halep kültürüyle Anadolu lezzetlerinin harmanlandığı, baharatın ve etin ustalıkla kullanıldığı zengin bir sofradır. Şehir, misafirperver halkı ve dar sokaklarındaki tarihi taş evleriyle kendine has bir ruh barındırır.'),
(52, 'Kocaeli', 41, 'Pişmaniye ve Kandıra Yoğurdu', 'Kocaeli, Marmara Bölgesi\'nin sanayi lokomotifi olmasının yanı sıra doğal güzellikleri ve körfez manzarasıyla da dikkat çeken bir şehirdir. Kartepe Kayak Merkezi, İstanbul\'a yakınlığıyla kış tatillerinin en popüler duraklarından biridir. Ormanya Doğal Yaşam Parkı, çocuklu aileler ve doğa yürüyüşçüleri için devasa bir alan sunar. Şehrin simgesi olan Pişmaniye, yüzyıllardır süregelen bir tatlı geleneğidir. Kandıra sahilleri (Kerpe, Kefken), temiz denizi ve ilginç kaya oluşumlarıyla yaz aylarında deniz tutkunlarını ağırlar.'),
(53, 'Konya', 42, 'Etli Ekmek ve Fırın Kebabı', 'Konya, Anadolu Selçuklu Devleti\'ne başkentlik yapmış, Mevlana Celaleddin Rumi\'nin hoşgörü felsefesiyle özdeşleşmiş manevi bir şehirdir. Mevlana Müzesi, her yıl dünyanın her yerinden gelen ziyaretçileri \"Gel, ne olursan ol yine gel\" çağrısıyla karşılar. Çatalhöyük Neolitik Kenti, insanlık tarihinin ilk yerleşik hayata geçiş noktalarından biri olarak UNESCO listesindedir. Konya Ovası, Türkiye\'nin \"tahıl ambarı\" olarak tarımda hayati bir role sahiptir. Selimiye Camii ve Meram Bağları, şehrin tarihi ve doğal güzelliklerini tamamlar.'),
(54, 'Kütahya', 43, 'Cimcik ve Sıkıcık Çorbası', 'Kütahya, çini ve porselen sanatının anavatanı olup Anadolu\'nun en köklü yerleşim yerlerinden biridir. Aizanoi Antik Kenti, dünyanın ilk ticaret borsasına ve en iyi korunmuş Zeus Tapınaklarından birine ev sahipliği yapar. Şehir merkezi, dar sokaklarındaki tarihi Kütahya Evleri ve çini atölyeleriyle el emeğinin her köşede hissedildiği bir yerdir. Germiyanoğulları Beyliği\'nin başkenti olması hasebiyle zengin bir saray mutfağı mirasına sahiptir. Şifalı kaplıcaları (Yoncalı, Ilıca), sağlık turizmi açısından bölgenin önemli merkezlerindendir.'),
(55, 'Malatya', 44, 'Kağıt Kebabı ve Analı Kızlı', 'Malatya, \"Kayısı Diyarı\" olarak bilinen, Doğu Anadolu\'nun modern ve misafirperver bir tarım-sanayi şehridir. Dünya kuru kayısı üretiminin yaklaşık %80\'ini karşılayarak ekonomiye devasa bir katkı sağlar. Arslantepe Höyüğü, UNESCO Dünya Mirası Listesi\'nde yer alan ve bürokrasinin doğuşuna tanıklık eden bir arkeolojik alandır. Tarihi Battalgazi bölgesi, Selçuklu dönemi eserleriyle şehrin manevi ruhunu yaşatır. Şehir, geniş caddeleri, düzenli kentleşmesi ve zengin bulgur temelli yemek kültürüyle bölgesinin cazibe merkezidir.'),
(56, 'Manisa', 45, 'Manisa Kebabı ve Mesir Macunu', 'Manisa, Osmanlı şehzadelerinin eğitim gördüğü \"Şehzadeler Şehri\" olarak bilinen, tarihi ve tarımsal zenginliği yüksek bir Ege kentidir. Spil Dağı Milli Parkı, yılkı atları ve endemik Manisa lalesiyle doğaseverler için eşsiz bir kaçış noktasıdır. Her yıl düzenlenen Mesir Macunu Festivali, asırlık bir şifa geleneğini yaşatan köklü bir etkinliktir. Antik Sardes kenti, Lidyalıların parayı ilk bastığı yer olarak tarihe geçmiştir. Şehir, verimli üzüm bağlarıyla Türkiye\'nin çekirdeksiz üzüm üretim merkezidir.'),
(57, 'Mardin', 47, 'Kaburga Dolması ve İçli Köfte', 'Mardin, Mezopotamya ovasına hakim bir tepede kurulu, taş evleri ve dar sokaklarıyla adeta bir masal şehridir. Farklı dinlerin ve dillerin yüzyıllardır barış içinde yaşadığı şehir, \"Hoşgörü Kenti\" olarak anılır. Mardin Müzesi, Zinciriye Medresesi ve Deyrulzafaran Manastırı, şehrin çok kültürlü mirasını yansıtan en önemli yapılardır. Akşamları ovanın ışıklarıyla birleşen taş mimari, \"Gecesi gerdanlık, gündüzü seyranlık\" sözünün hakkını verir. Telkari (gümüş işleme) sanatı, Mardinli ustaların elinde hayat bulan en zarif zanaattır.'),
(58, 'Mersin', 33, 'Tantuni ve Cezerye', 'Mersin, Doğu Akdeniz\'in en büyük limanına ev sahipliği yapan, palmiye ağaçlarıyla süslü uzun sahil şeridiyle dikkat çeken bir şehirdir. Kızkalesi, denizin ortasındaki efsanevi duruşuyla şehrin en önemli turistik simgesidir. Cennet ve Cehennem obrukları ile Astım Mağarası, doğanın oluşturduğu etkileyici jeolojik yapılardır. Tarsus ilçesi, St. Paul Kuyusu ve Danyal Peygamber Kabri ile inanç turizminin önemli duraklarındandır. Şehir, narenciye üretimi ve muz bahçeleriyle tarımın, dev limanıyla da ticaretin kalbidir.'),
(59, 'Muğla', 48, 'Muğla Köftesi ve Çökertme Kebabı', 'Muğla, Bodrum, Marmaris, Fethiye ve Datça gibi dünyaca ünlü tatil cennetlerini barındıran Türkiye\'nin turizm amiral gemisidir. Şehir, kristal berraklığındaki koyları, antik kentleri ve çam ormanlarıyla doğa ve denizin mükemmel birleşimini sunar. Ölüdeniz ve Kelebekler Vadisi, kartpostalları süsleyen eşsiz manzaralarıyla her yıl milyonlarca turisti çeker. Muğla şehir merkezi, bacalarıyla ünlü beyaz boyalı evleri ve dar sokaklarıyla sakin bir Ege kasabası atmosferini korur. Şehir, mavi yolculuğun doğduğu yer olup yat turizminde dünya markasıdır.'),
(60, 'Muş', 49, 'Muş Köftesi ve Çorti', 'Muş, Anadolu kapılarının Türklere açıldığı Malazgirt Ovası ile tarih sahnesinde kritik bir öneme sahip olan bir Doğu Anadolu şehridir. Bahar aylarında ovanın her yanını kaplayan kırmızı laleler (Muş Lalesi), şehre görsel bir şölen kazandırır. Tarihi Murat Köprüsü, Murat Nehri üzerinde asırlardır ayakta duran şehrin en önemli simgelerinden biridir. Şehir, tarım ve hayvancılığa dayalı ekonomisi ve geniş otlaklarıyla bilinir. Malazgirt Zaferi kutlamaları, her yıl milli bir coşkuyla bu topraklarda gerçekleştirilir.'),
(61, 'Nevşehir', 50, 'Testi Kebabı', 'Nevşehir, dünyanın en ilginç jeolojik oluşumlarından biri olan Kapadokya bölgesinin kalbidir. Peri bacaları, yer altı şehirleri (Derinkuyu, Kaymaklı) ve kayalara oyulmuş kiliseleriyle UNESCO Dünya Mirası Listesi\'nin en nadide parçalarındandır. Göreme Milli Parkı\'nda gün doğumunda havalanan sıcak hava balonları, şehre rüya gibi bir siluet kazandırır. Avanos ilçesi, Kızılırmak\'tan alınan çamurla yapılan çömlekçilik geleneğiyle ünlüdür. Şarap üretimi ve butik kaya otelleriyle turizmde özgün bir deneyim sunan şehir, her mevsim büyüleyicidir.'),
(62, 'Niğde', 51, 'Niğde Tavası ve Niğde Gazozu', 'Niğde, İç Anadolu\'nun güneyinde yer alan, heybetli Aladağlar\'ı ve zengin elma bahçeleriyle tanınan köklü bir şehirdir. Gümüşler Manastırı, içindeki gülen Meryem Ana freskiyle Hristiyanlık tarihi için eşsiz bir öneme sahiptir. Selçuklu mimarisinin incisi olan Alaaddin Camii, belirli saatlerde oluşan \"Taçlı Kadın\" gölgesiyle bir mühendislik harikasıdır. Şehir, Türkiye\'nin en büyük patates ve elma üretim merkezlerinden biri olarak tarıma yön verir. Aladağlar, dağcılık ve tırmanış sporları için dünyanın dört bir yanından gelen sporcuları ağırlar.'),
(63, 'Ordu', 52, 'Ordu Tostu ve Balık Buğulama', 'Ordu, \"Derelerin Özgür Aktığı Şehir\" olarak bilinen, fındık bahçeleri ile sahilin iç içe geçtiği bir Karadeniz güzelliğidir. Boztepe, teleferikle çıkılan ve tüm şehrin ayaklar altına serildiği muazzam manzarasıyla ünlüdür. Perşembe Yaylası\'ndaki menderesler, doğanın çizdiği kusursuz birer sanat eseri gibi vadi boyunca uzanır. Yason Burnu, üzerindeki tarihi kilisesi ve deniz manzarasıyla mitolojik hikayelere ev sahipliği yapmış sakin bir duraktır. Dünyanın en kaliteli fındığının yetiştiği şehir, çikolata ve fındık sanayisiyle de gelişmektedir.'),
(64, 'Osmaniye', 80, 'Osmaniye Yer Fıstığı ve Tirşik', 'Osmaniye, Çukurova\'nın doğusunda yer alan, kaleleriyle ünlü ve Türkiye\'nin yer fıstığı ambarı olarak bilinen bir tarım şehridir. Kastabala Antik Kenti ve sarp kayalıklara kurulu Yılanlı Kale, şehrin tarihsel gücünü ve savunma geçmişini simgeler. Karatepe-Aslantaş Milli Parkı, Hitit hiyeroglif yazılarının çözüldüğü açık hava müzesiyle dünya arkeoloji tarihinde kritik bir yere sahiptir. Şehir, Amanos Dağları\'nın eteğinde verimli ovalarıyla hem tarımın hem de sanayinin geliştiği bir merkezdir. Yer fıstığı, şehrin ekonomisinin ve günlük yaşamının ayrılmaz bir parçasıdır.'),
(65, 'Rize', 53, 'Muhlama ve Rize Kavurması', 'Rize, Türkiye\'nin en çok yağış alan, çay bahçeleriyle yemyeşil bir örtüye bürünmüş hırçın Karadeniz şehridir. Ayder ve Anzer yaylaları, şifalı balları ve bulutların üzerindeki evleriyle doğaseverlerin vazgeçilmezidir. Fırtına Deresi üzerinde kurulu tarihi taş köprüler, bölgenin mimari ve kültürel simgeleridir. Kaçkar Dağları, raftingden heliski’ye (helikopterli kayak) kadar birçok doğa sporu için dünya çapında bir merkezdir. Şehir, Türkiye\'nin çay ihtiyacının büyük kısmını karşılar ve çay kültürü şehrin her sokağına işlemiştir.'),
(66, 'Sakarya', 54, 'Islama Köfte ve Kabak Tatlısı', 'Sakarya, Marmara Bölgesi\'nin doğusunda yer alan, gölleri, nehirleri ve tarım-sanayi çeşitliliğiyle dikkat çeken dinamik bir şehirdir. Sapanca Gölü, çevresindeki konaklama tesisleri ve doğasıyla hafta sonu kaçamaklarının bir numaralı adresidir. Sakarya Nehri\'nin suladığı verimli ovalar, şehri tarımsal bir güç haline getirmiştir. Tarihi Justinianus Köprüsü (Beşköprü), Roma döneminin görkemli mühendislik izlerini taşır. Karasu sahilleri, Karadeniz\'e açılan kapısı olarak yaz aylarında tatilcileri ağırlar. Şehir, farklı kültürlerin bir arada yaşadığı zengin bir demografik yapıya sahiptir.'),
(67, 'Samsun', 55, 'Bafra Pidesi ve Nokul', 'Samsun, Gazi Mustafa Kemal Atatürk\'ün 19 Mayıs 1919\'da ayak bastığı ve Milli Mücadele meşalesini yaktığı \"Kurtuluş Şehri\"dir. Bandırma Vapuru Müzesi ve Onur Anıtı, şehrin bu şanlı tarihini simgeleyen en önemli duraklardır. Karadeniz\'in en büyük kenti olması hasebiyle ticaret, eğitim ve sağlıkta bölgenin merkezidir. Kızılırmak Deltası Kuş Cenneti, yüzlerce kuş türüne ev sahipliği yapan devasa bir ekosistemdir. Şehir, sahil boyunca uzanan geniş parkları, modern marinası ve canlı sosyal yaşamıyla Karadeniz\'in yükselen değeridir.'),
(68, 'Siirt', 56, 'Büryan Kebabı ve Perde Pilavı', 'Siirt, Güneydoğu Anadolu\'nun dağlık ve engebeli coğrafyasında saklı, zengin bir mutfak kültürüne ve manevi değere sahip bir şehirdir. Tillo (Aydınlar) ilçesi, İbrahim Hakkı Hazretleri\'nin güneş düzeneği gibi bilimsel ve dini mirasıyla tanınır. Şehir, ince kabuklu Siirt fıstığı ve şifa kaynağı Pervari balı ile tarımsal markalara sahiptir. Botan Çayı ve üzerindeki kanyonlar, doğa tutkunları için eşsiz manzaralar sunan yeni keşfedilen rotalardır. Siirt battaniyesi, tiftikten elde edilen geleneksel bir el sanatı olarak varlığını korur.'),
(69, 'Sinop', 57, 'Sinop Mantısı ve Nokul', 'Sinop, Türkiye\'nin en kuzey noktası olan İnceburun\'a ev sahipliği yapan, mutluluk oranı en yüksek şehirlerin başında gelir. Tarihi Sinop Cezaevi, birçok ünlü ismi ağırlamış \"Anadolu\'nun Alkatrazı\" olarak bilinen etkileyici bir yapıdır. Hamsilos Koyu, Türkiye\'nin tek fiyordu olarak adlandırılan ve çam ağaçlarının denize kadar indiği bir doğa harikasıdır. Şehir, antik çağların filozofu Diyojen\'in memleketi olup, sahilindeki balıkçı tekneleri ve huzurlu yaşamıyla bilinir. Erfelek Tatlıca Şelaleleri, art arda sıralanmış 28 şelalesiyle doğa yürüyüşçülerini bekler.'),
(70, 'Sivas', 58, 'Sivas Köftesi ve Pesahutan', 'Sivas, Selçuklu mimarisinin görkemini taşıyan ve Milli Mücadele\'nin en önemli kararlarının alındığı bir cumhuriyet şehridir. UNESCO Dünya Mirası Listesi\'ndeki Divriği Ulu Camii ve Darüşşifası, taş işçiliğindeki detaylarıyla \"Anadolu\'nun El Hamra\'sı\" olarak anılır. Gök Medrese ve Çifte Minareli Medrese, şehir merkezindeki tarihi meydanın görkemini tamamlar. Kangal Çoban Köpeği, zekası ve sadakatiyle dünya çapında tanınan şehrin en önemli canlı değeridir. Kangal Balıklı Kaplıcası, sedef hastalığı gibi cilt sorunlarına sunduğu tedaviyle dünyaca ünlüdür.'),
(71, 'Şanlıurfa', 63, 'Çiğ Köfte ve Urfa Kebabı', 'Şanlıurfa, \"Peygamberler Şehri\" olarak bilinen ve insanlık tarihinin sıfır noktası kabul edilen Göbeklitepe\'ye ev sahipliği yapan kadim bir şehirdir. Balıklıgöl, manevi atmosferi ve efsaneleriyle şehrin en önemli simgesidir. Harran Evleri, konik kubbeli mimarisiyle dünyada eşi benzeri olmayan bir yerleşim düzeni sunar. Tarihi çarşıları, baharat kokuları ve sıra geceleri geleneğiyle Urfa, Mezopotamya\'nın kültürel kalbidir. Şehir, Halfeti\'nin batık köyü ve dünyada sadece burada yetişen Karagül ile gizemli bir güzelliğe de sahiptir.'),
(72, 'Şırnak', 73, 'Kutlık ve Serubew', 'Şırnak, Cudi Dağı\'nın eteklerinde kurulu, Hz. Nuh\'un gemisinin karaya oturduğu yer olarak inanılan kadim bir sınır şehridir. Kasrik Boğazı, doğanın aşındırmasıyla oluşmuş kapı gibi duruşuyla şehrin en stratejik ve manzaralı geçiş noktasıdır. Tarihi Mem-u Zin Türbesi, bölgenin destansı aşk hikayesinin manevi evidir. Şehir, son yıllarda keşfedilen petrol rezervleri ve gelişen altyapısıyla enerji sektöründe adından söz ettirmektedir. Cizre ilçesi, kırmızı medresesi ve tarihi eserleriyle bölgenin ilim ve kültür merkezi olma özelliğini yüzyıllardır korur.'),
(73, 'Tekirdağ', 59, 'Tekirdağ Köftesi ve Hayrabolu Tatlısı', 'Tekirdağ, Marmara Denizi kıyısında uzanan verimli toprakları, ayçiçeği tarlaları ve meşhur köftesiyle Trakya\'nın parlayan yıldızıdır. Şehir, üzüm bağları ve bağ bozumu şenlikleriyle gastronomi turizminde önemli bir yere sahiptir. Namık Kemal Evi Müzesi, \"Vatan Şairi\"nin anısını yaşatan şehrin kültürel duraklarındandır. Uçmakdere, yamaç paraşütü tutkunları için Marmara Denizi manzaralı eşsiz bir uçuş noktası sunar. Şehir, modern limanları ve gelişmiş sanayisiyle Avrupa ile Anadolu arasındaki geçiş güzergahında kritik bir ticaret merkezidir.'),
(74, 'Tokat', 60, 'Tokat Kebabı ve Tokat Pağacı', 'Tokat, \"900 Adımda 900 Yıl\" sloganıyla her sokağında farklı bir devrin izini taşıyan köklü bir Anadolu şehridir. Ballıca Mağarası, içindeki nadir kristal oluşumlarıyla dünyanın sayılı mağaraları arasında yer alır. Şehir merkezi; tarihi Taşhan, saat kulesi ve Selçuklu köprüleriyle tarih meraklıları için bir hazinedir. Tokat yaprağı, kalitesi ve aromasıyla Türkiye\'nin en çok aranan sarmalık yaprağıdır. Niksar ve Zile gibi ilçeleri, kaleleri ve tarihi dokusuyla Karadeniz ile İç Anadolu arasındaki kültürel sentezi yansıtır.'),
(75, 'Trabzon', 61, 'Akçaabat Köftesi ve Hamsili Pilav', 'Trabzon, Karadeniz\'in hırçın dalgaları ile sarp dağlarının kucaklaştığı, binlerce yıllık liman kenti ve ticaret merkezidir. Sümela Manastırı, dik kayalıklara oyulmuş mimarisiyle inanç turizminin ve doğanın en etkileyici birleşimlerinden biridir. Uzungöl, sisli manzarası ve göl etrafındaki tesisleriyle şehrin en popüler turizm destinasyonudur. Ayasofya Müzesi ve Atatürk Köşkü, şehrin mimari zenginliğini tamamlar. Futbol tutkusu ve kemençe eşliğindeki horonuyla bilinen Trabzon, enerjisi yüksek ve kendine has kültürü olan bir metropoldür.'),
(76, 'Tunceli', 62, 'Şavak Tulum Peyniri ve Zerefet', 'Tunceli, Munzur Vadisi Milli Parkı\'nın el değmemiş doğası, berrak suları ve sarp dağlarıyla bilinen huzurlu bir Doğu Anadolu şehridir. Munzur Gözeleri, inanç turizmi ve doğal güzelliği bir araya getiren şehrin en kutsal ve manzaralı noktasıdır. Pülümür Vadisi, doğa sporları ve fotoğrafçılık için vahşi bir doğa sunar. Şehir, Türkiye\'nin okuryazarlık oranı en yüksek illerinden biri olmasıyla kültürel bir fark yaratır. Ovacık ilçesi, organik tarımı ve kooperatifçilik başarılarıyla son yıllarda adından sıkça söz ettirmektedir.'),
(77, 'Uşak', 64, 'Uşak Tarhanası', 'Uşak, Ege ile İç Anadolu arasında köprü kuran, battaniye ve deri sanayisiyle tanınan bir üretim şehridir. Dünyanın en büyük ikinci kanyonu olarak kabul edilen Ulubey Kanyonu, cam terasıyla doğaseverlere adrenalin dolu bir manzara sunar. Karun Hazineleri\'nin sergilendiği Uşak Arkeoloji Müzesi, \"Kanatlı Denizatı Broşu\" gibi paha biçilemez tarihi eserleri barındırır. Şehir, \"İlkler Şehri\" olarak bilinir; Türkiye\'de ilk şeker fabrikasının kurulduğu ve ilk kez elektriğin kullanıldığı yerlerden biridir. Tarhana üretimi, şehrin en önemli gastronomi markasıdır.'),
(78, 'Van', 65, 'Van Kahvaltısı ve İnci Kefali', 'Van, \"Doğu\'nun İncisi\" olarak anılan, Türkiye\'nin en büyük gölü olan Van Gölü\'ne (Van Denizi) ev sahipliği yapan kadim bir Urartu başkentidir. Akdamar Adası ve üzerindeki tarihi kilise, taş işçiliği ve gölün turkuaz suyuyla muazzam bir uyum içindedir. Van Kalesi, Urartulardan kalan görkemiyle şehri tepeden izleyen bir tarih anıtıdır. Şehir, dünyaca ünlü kehribar gözlü Van Kedisi ve zengin Van kahvaltısı kültürüyle her yıl binlerce ziyaretçiyi ağırlar. Muradiye Şelalesi, özellikle kışın donduğunda ve baharda gürlediğinde doğaseverler için eşsizdir.');
INSERT INTO `sehirler` (`id`, `sehir_adi`, `plaka_kodu`, `meshur_yemek`, `kisa_bilgi`) VALUES
(79, 'Yalova', 77, 'Yalova Sütlüsü', 'Yalova, Marmara Denizi kıyısında, şifalı kaplıcaları ve yeşil bitki örtüsüyle \"İstanbul\'un bahçesi\" olarak anılan huzurlu bir şehirdir. Termal ilçesi, Roma döneminden beri kullanılan şifalı suları ve asırlık çınar ağaçlarıyla sağlık turizminin merkezidir. Yürüyen Köşk, Atatürk\'ün doğa sevgisini simgeleyen ve bir ağaç dalı için raylar üzerinde kaydırılan dünyaca ünlü çevreci bir anıttır. Karaca Arboretumu, Türkiye\'nin ilk özel ağaç parkı olup binlerce bitki türüne ev sahipliği yapar. Şehir, çiçekçilik ve süs bitkileri üretiminde Türkiye\'nin lider illerinden biri olup modern bir kent yapısına sahiptir.'),
(80, 'Yozgat', 66, 'Testi Kebabı ve Yozgat Parmak Çöreği', 'Yozgat, İç Anadolu\'nun orta kesiminde yer alan, geniş yaylaları ve Türkiye\'nin ilk milli parkı olan Yozgat Çamlığı ile bilinen bir şehirdir. Çamlık Milli Parkı, asırlık karaçam ağaçlarıyla şehrin akciğeri konumundadır. Sarıkaya ilçesindeki \"Kral Kızı\" adıyla bilinen Roma Hamamı (Basilica Therma), UNESCO geçici listesinde yer alan şifalı bir antik mirastır. Şehir, tarihi saat kulesi ve Osmanlı döneminden kalma Çapanoğlu Camii ile kültürel siluetini tamamlar. Hayvancılık ve tahıl üretiminde bölgenin önemli merkezlerinden biridir.'),
(81, 'Zonguldak', 67, 'Ereğli Pidesi ve Malay', 'Zonguldak, \"Emeğin Başkenti\" olarak bilinen, Türkiye\'nin en zengin taş kömürü yataklarına ve köklü bir madencilik kültürüne sahip sahil şehridir. Şehir, sarp kayalıklar üzerine kurulu yapısı ve modern limanıyla Batı Karadeniz\'in sanayi merkezidir. Gökgöl Mağarası, ışıklandırılmış yürüyüş yolları ve damlataş oluşumlarıyla yer altının gizemli dünyasını sunar. Ereğli ilçesindeki Cehennemağzı Mağaraları, mitolojik öyküleri ve antik kalıntılarıyla tarihe ışık tutar. Maden Müzesi, şehrin kimliğini oluşturan yer altı işçiliğini tüm detaylarıyla ziyaretçilere aktarır.');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `sehirler`
--
ALTER TABLE `sehirler`
  ADD PRIMARY KEY (`id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `sehirler`
--
ALTER TABLE `sehirler`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=82;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
